### ISSUE TITLE
SQLITE_BUSY: database is locked - After register new user

### ISSUE THREAD

**Issue by ricardojlrufino** [reesvarney/OpenChat#15]
```
Database ✔
Signalling ✔
Controllers ✔
HTTPS Server ✔
No owners found, entering setup mode - first client to join will be given owner role
MCU Client ✔
/usr/src/openchat/node_modules/sequelize/lib/dialects/sqlite/query.js:412
        return new sequelizeErrors.TimeoutError(err);
               ^

TimeoutError [SequelizeTimeoutError]: SQLITE_BUSY: database is locked
    at Query.formatError (/usr/src/openchat/node_modules/sequelize/lib/dialects/sqlite/query.js:412:16)
    at Query._handleQueryResponse (/usr/src/openchat/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at Statement.afterExecute (/usr/src/openchat/node_modules/sequelize/lib/dialects/sqlite/query.js:246:27) {
  parent: [Error: SQLITE_BUSY: database is locked] {
    errno: 5,
    code: 'SQLITE_BUSY',
    sql: 'INSERT INTO `Roles` (`id`,`name`,`isAdmin`,`permission_join`,`permission_speak`,`permission_listen`,`permission_send_message`,`permission_move`,`permission_ban`,`permission_kick`,`permission_mute`,`permission_deafen`,`permission_delete_message`,`permission_edit_channels`,`permission_edit_server`,`permission_edit_roles`,`createdAt`,`updatedAt`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18);'
  },
  original: [Error: SQLITE_BUSY: database is locked] {
    errno: 5,
    code: 'SQLITE_BUSY',
    sql: 'INSERT INTO `Roles` (`id`,`name`,`isAdmin`,`permission_join`,`permission_speak`,`permission_listen`,`permission_send_message`,`permission_move`,`permission_ban`,`permission_kick`,`permission_mute`,`permission_deafen`,`permission_delete_message`,`permission_edit_channels`,`permission_edit_server`,`permission_edit_roles`,`createdAt`,`updatedAt`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18);'
  },
  sql: 'INSERT INTO `Roles` (`id`,`name`,`isAdmin`,`permission_join`,`permission_speak`,`permission_listen`,`permission_send_message`,`permission_move`,`permission_ban`,`permission_kick`,`permission_mute`,`permission_deafen`,`permission_delete_message`,`permission_edit_channels`,`permission_edit_server`,`permission_edit_roles`,`createdAt`,`updatedAt`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18);',
  parameters: undefined
}
```

Using docker version.

**Comment by ricardojlrufino** [comment]
Same building from dockerfile

**Comment by reesvarney** [comment]
I'm not too sure what's causing this as the demo server runs off docker and didn't experience this kind of issue. I'm currently working on an overhaul of some of the voice systems but once it is finished, I will make sure to investigate this issue.

For the time being, just make sure that you give the server a good few minutes before trying to register, this kind of error occurs when the database is being written to by another part of the code and I assume this must be from the database seeding or something.

I will update here if I manage to find a more definitive fix.
